sudo: required
services:
  - docker

before_install:
  - docker build -t brs97/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run brs97/react-test npm test -- --coverage

after_success:
  - docker build -t brs97/multi-client ./client
  - docker build -t brs97/multi-nginx ./nginx
  - docker build -t brs97/multi-server ./server
  - docker build -t brs97/multi-worker ./worker
  
